package com.example.cs_office.Util;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public class PathResources {

    public static final String SAVE = "/insert";
    public static final String DELETEBYID = "/delete/{id}";
    public static final String UPDATEBYID = "/update/{id}";
    public static final String UPDATESTATUSFALSE = "/updatestatusfalse";
    public static final String UPDATESTATUSTRUE = "/updatestatustrue";
    public static final String FIND_ALL = "/find_all";
    public static final String FIND_BY_STATUSFALSE = "/find_by_status/false";
    public static final String FIND_BY_STATUSTRUE = "/find_by_status/true";
    public static final String FIND_BY_ID = "/find_by_id/{id}";
    public static final String FIND_BY_NAME = "/find_by_name/{name}";
    public static final String FIND_BY_EMAIL = "/find_by_email";
    public static final String FIND_BY_FLNAME = "/find_by_name/{firstname}/{lastname}";
    public static final String FIND_STAFF = "/find_staff";
    public static final String LOGIN = "/hanoioffice/login";
    public static final String LOGOUT = "/hanoioffice/logout";
    public static final String REGISTER = "/register";
    public static final String INSERTSTAFF = "/staff/insert";
    public static final String FORGOTPASSWORD = "/forgotpassword";
    public static final String CUSTOMERCHANGEPASSWORD = "/customer/changepassword/{customerId}";
    public static final String STAFFCHANGEPASSWORD = "/staff/changepassword/{staffId}";
    public static final String RESETPASSWORD = "/resetpassword";
    public static final String BRANCH = "/branch";
    public static final String CUSTOMER = "/customer";
    public static final String DATEMASTER = "/datemaster";
    public static final String EVALUATE = "/evaluate";
    public static final String ORDERDETAIL = "/orderdetail";
    public static final String ORDERHISTORY = "/orderhistory";
    public static final String ORDER = "/order";
    public static final String PRICESERVICE = "/priceservice";
    public static final String PRICETYPEROOM = "/pricetyperoom";
    public static final String ROLE = "/role";
    public static final String ROOM = "/room";
    public static final String SCHEDULEDETAIL = "/scheduledetail";
    public static final String SCHEDULE = "/schedule";
    public static final String SERVICE = "/service";
    public static final String SERVICEDETAIL = "/servicedetail";
    public static final String SHIFT = "/shift";
    public static final String STAFF = "/staff";
    public static final String TYPEROOM = "/typeroom";
    public static final String COUNTORDERDETAIL = "/countorderdetail";
    public static final String BOOK = "/book";
    public static final String LISTROOM = "/listRoom/{idTypeRoom}/{idBranch}";
    public static final String BOOKROOMLT = "/bookroomlt";
    public static final String CHECKROOMBYID = "/checkroombyid/{idRoom}";
    public static final String LISTBOOKROOM = "/listbookroom";
    public static final String LISTBOOKROOMACCEPT = "/listbookroomaccept";
    public static final String LISTBOOKROOMHISTORY = "/listbookroomhistory";
    public static final String LISTBOOKROOMADMIN = "/listbookroomadmin";
    public static final String LISTBOOKROOMCUSTOMER = "/listbookroomcustomer";
    public static final String LISTBOOKROOMCUSTOMERHISTORY = "/listbookroomcustomerhistory";
    public static final String ACCEPT = "/accept/{idOrderDetail}";
    public static final String CANCEL = "/cancel/{idOrderDetail}";
    public static final String LISTROOMSALE = "/listRoomSale/{idTypeRoom}/{idBranch}";
    public static final String ROOKBOOKDETAILSALE = "/roombookdetailsale";
    public static final String ROOKBOOKLETAN = "/roombookletan";
    public static final String CHECKINOUTLETAN = "/checkinout";
    public static final String BOOKROOMKTL = "bookroomklt";
    public static final String LISTIFBYENDSTART = "listifbyendstart";
    public static final String SEARCHROOM = "searchRoom";
    public static final String SEARCHR = "searchroom";
    public static final String TEST = "test";
    public static final String TOTALBYIDORDETAIL = "totalbyid";
    public static final String TOTALBYDATE = "totalbydate";
    public static final String TOTAL = "total";
    public static final String SALEACCEPT = "saleaccept";
    public static final String SALEACCEPTUPDATE = "saleacceptupdate";
    public static final String SALENOTACCEPT = "salenotaccept";
    public static final String UPDATEDONE = "updatedone";
}
